name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  compile_and_test:
    name: Test
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
    - name: Compile library
      run: |
            gcc -O3 -fPIC -mssse3 -mpclmul -c crc.c
            gcc -shared crc.o -o crc.dll
    - name: Run test
      run: python test.py
